### ISSUE TITLE
Regarding Push service API

### ISSUE THREAD

**Issue by shankarmohannamakkal** [hhimanshu/web-push-notifications#1]
Hi @hhimanshu 

Should I use any third party push service API like firebase for my official app or should I create this as my own separately. I am not clear on this and little confuse. 

Could you help to share your thoughts with me?
Thank you

**Comment by hhimanshu** [comment]
Yes, you would need a push service. I have covered that in module 04 at https://www.pluralsight.com/courses/web-push-notifications-deep-dive. I hope that helps
